/**
 * Created by thomasschuessler on 31.03.16.
 */

var glieder = {
    /* Arm Links */
    1: {
        displayName: "Arm -li",
        name: "Arm links",
        tax: "70",
        groupId: "1",
        image: "",
        siblingId: "8",
        siblingGroup: "2",
        selected: false,
        optionVisible: false,
    },
    2: {
        displayName: "Arm bis oberhalb Ellenbogen -li",
        name: "Arm bis oberhalb Ellenbogen links",
        tax: "65",
        groupId: "1",
        image: "",
        siblingId: "9",
        siblingGroup: "2",
        selected: false,
        optionVisible: false,
    },
    3: {
        displayName: "Arm unterhalb Ellenbogen -li",
        name: "Arm unterhalb Ellenbogen links",
        tax: "60",
        groupId: "1",
        image: "",
        siblingId: "10",
        siblingGroup: "2",
        selected: false,
        optionVisible: false,
    },
    4: {
        displayName: "Hand -li",
        name: "Hand links",
        tax: "55",
        groupId: "1",
        image: "",
        siblingId: "11",
        siblingGroup: "2",
        selected: false,
        optionVisible: false,
    },
    5: {
        displayName: "Daumen -li",
        name: "Daumen links",
        tax: "20",
        groupId: "1",
        image: "",
        siblingId: "12",
        siblingGroup: "2",
        selected: false,
        optionVisible: false,
    },
    6: {
        displayName: "Zeigefinger -li",
        name: "Zeigefinger links",
        tax: "10",
        groupId: "1",
        image: "",
        siblingId: "13",
        siblingGroup: "2",
        selected: false,
        optionVisible: false,
    },
    7: {
        displayName: "anderer Finger -li",
        name: "anderer Finger links",
        tax: "5",
        groupId: "1",
        image: "",
        siblingId: "14",
        siblingGroup: "2",
        selected: false,
        optionVisible: false,
    },

    /* Arm rechts */
    8: {
        displayName: "Arm -re",
        name: "Arm rechts",
        tax: "70",
        groupId: "2",
        image: "",
        siblingId: "1",
        siblingGroup: "1",
        selected: false,
        optionVisible: false,
    },
    9: {
        displayName: "Arm bis oberhalb Ellenbogen -re",
        name: "Arm bis oberhalb Ellenbogen rechts",
        tax: "65",
        groupId: "2",
        image: "",
        siblingId: "2",
        siblingGroup: "1",
        selected: false,
        optionVisible: false,
    },
    10: {
        displayName: "Arm unterhalb Ellenbogen -re",
        name: "Arm unterhalb Ellenbogen rechts",
        tax: "60",
        groupId: "2",
        image: "",
        siblingId: "3",
        siblingGroup: "1",
        selected: false,
        optionVisible: false,
    },
    11: {
        displayName: "Hand -re",
        name: "Hand rechts",
        tax: "55",
        groupId: "2",
        image: "",
        siblingId: "4",
        siblingGroup: "1",
        selected: false,
        optionVisible: false,
    },
    12: {
        displayName: "Daumen -re",
        name: "Daumen rechts",
        tax: "20",
        groupId: "2",
        image: "",
        siblingId: "5",
        siblingGroup: "1",
        selected: false,
        optionVisible: false,
    },
    13: {
        displayName: "Zeigefinger -re",
        name: "Zeigefinger rechts",
        tax: "10",
        groupId: "2",
        image: "",
        siblingId: "6",
        siblingGroup: "1",
        selected: false,
        optionVisible: false,
    },
    14: {
        displayName: "anderer Finger -re",
        name: "anderer Finger rechts",
        tax: "5",
        groupId: "2",
        image: "",
        siblingId: "7",
        siblingGroup: "1",
        selected: false,
        optionVisible: false,
    },
    15: {
        displayName: "Verlust der Milz",
        name: "Verlust der Milz",
        tax: "10",
        groupId: "3",
        image: "",
        siblingId: false,
        siblingGroup: false,
        selected: false,
        optionVisible: false,
    },
    16: {
        displayName: "Sprechvermögen",
        name: "Sprechvermögen",
        tax: "60",
        groupId: "4",
        image: "",
        siblingId: false,
        siblingGroup: false,
        selected: false,
        optionVisible: false,
    },
    /* Bein Links */
    17: {
        displayName: "Bein über Mitte Oberschenkel -li",
        name: "Bein über Mitte Oberschenkel links",
        tax: "70",
        groupId: "5",
        image: "",
        siblingId: "24",
        siblingGroup: "6",
        selected: false,
        optionVisible: false,
    },
    18: {
        displayName: "Bein bis Mitte Oberschenkel -li",
        name: "Bein bis Mitte Oberschenkel links",
        tax: "60",
        groupId: "5",
        image: "",
        siblingId: "25",
        siblingGroup: "6",
        selected: false,
        optionVisible: false,
    },
    19: {
        displayName: "Bein bis unterhalb Knies -li",
        name: "Bein bis unterhalb Knies links",
        tax: "50",
        groupId: "5",
        image: "",
        siblingId: "26",
        siblingGroup: "6",
        selected: false,
        optionVisible: false,
    },
    20: {
        displayName: "Bein bis Mitte Unterschenkel  -li",
        name: "Bein bis Mitte Unterschenkel links",
        tax: "45",
        groupId: "5",
        image: "",
        siblingId: "27",
        siblingGroup: "6",
        selected: false,
        optionVisible: false,
    },
    21: {
        displayName: "Fuß -li",
        name: "Fuß links",
        tax: "70",
        groupId: "5",
        image: "",
        siblingId: "28",
        siblingGroup: "6",
        selected: false,
        optionVisible: false,
    },
    22: {
        displayName: "große Zehe -li",
        name: "große Zehe links",
        tax: "5",
        groupId: "5",
        image: "",
        siblingId: "29",
        siblingGroup: "6",
        selected: false,
        optionVisible: false,
    },
    23: {
        displayName: "andere Zehe -li",
        name: "andere Zehe links",
        tax: "2",
        groupId: "5",
        image: "",
        siblingId: "30",
        siblingGroup: "6",
        selected: false,
        optionVisible: false,
    },
    /* Bein Rechts */
    24: {
        displayName: "Bein über Mitte Oberschenkel -re",
        name: "Bein über Mitte Oberschenkel rechts",
        tax: "70",
        groupId: "6",
        image: "",
        siblingId: "17",
        siblingGroup: "5",
        selected: false,
        optionVisible: false,
    },
    25: {
        displayName: "Bein bis Mitte Oberschenkel -re",
        name: "Bein bis Mitte Oberschenkel rechts",
        tax: "60",
        groupId: "6",
        image: "",
        siblingId: "18",
        siblingGroup: "5",
        selected: false,
        optionVisible: false,
    },
    26: {
        displayName: "Bein bis unterhalb Knies -re",
        name: "Bein bis unterhalb Knies rechts",
        tax: "50",
        groupId: "6",
        image: "",
        siblingId: "19",
        siblingGroup: "5",
        selected: false,
        optionVisible: false,
    },
    27: {
        displayName: "Bein bis Mitte Unterschenkel  -re",
        name: "Bein bis Mitte Unterschenkel rechts",
        tax: "45",
        groupId: "6",
        image: "",
        siblingId: "20",
        siblingGroup: "5",
        selected: false,
        optionVisible: false,
    },
    28: {
        displayName: "Fuß -re",
        name: "Fuß rechts",
        tax: "70",
        groupId: "6",
        image: "",
        siblingId: "21",
        siblingGroup: "5",
        selected: false,
        optionVisible: false,
    },
    29: {
        displayName: "große Zehe -re",
        name: "große Zehe rechts",
        tax: "5",
        groupId: "6",
        image: "",
        siblingId: "22",
        siblingGroup: "5",
        selected: false,
        optionVisible: false,
    },
    30: {
        displayName: "andere Zehe -re",
        name: "andere Zehe rechts",
        tax: "2",
        groupId: "6",
        image: "",
        siblingId: "23",
        siblingGroup: "5",
        selected: false,
        optionVisible: false,
    },
}


